### ISSUE TITLE
clarify support for idea that viral mutations are associated with IFN

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/IFNsorted_flu_single_cell#18]
While we demonstrate that *specific mutations* enhance IFN induction, appropriately acknowledge / caveat the fact that there isn't an overall significant association between mutation load and IFN. This is likely because there are also many non-stimulatory mutations that dilute the signal, plus we have limited cell numbers.

**Comment by abr28** [comment]
Agree. I do think fundamentally this is a numbers issue–given reasonable assumptions about non-functional versus functional mutations. I think simply stressing that this approach tells us the absolute genetic requirements (or lack thereof) of IFN induction lets us off easy in terms of also developing a holistic model.

**Comment by jbloom** [comment]
Text now clearly emphasizes that there is not **statistical** support for most associations, but that they are validated by follow-up work.
