### ISSUE TITLE
clarify colors in Figure 4

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/IFNsorted_flu_single_cell#19]
Make clear that light versus dark blue show *number* of viral variants, not which barcode. Also clarify that cells with polymerase deletions that have high viral mRNA are *co-infected* with a deletion and wildtype virus. This is in figure, but explanation should be more explicit.

**Comment by abr28** [comment]
Will think if there is a way to improve on this, but definitely agree given the reviewer's confusion.

**Comment by jbloom** [comment]
Legend now clarifies this fact.
