### ISSUE TITLE
clarify heterogeneity in Figure 6

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/IFNsorted_flu_single_cell#21]
Clearly mention that the flow cytometry data in Figure 6 is itself the result of single-cell measurements, and so shows that there is heterogeneity even in the mutant viruses tested in this figure.

**Comment by abr28** [comment]
I think going along with prior comment of noting non-deterministic behavior should be fine (doesn't work for the deletion as we didn't use HA-gating, but would work for all other mutations).

**Comment by jbloom** [comment]
Last section of results ends with paragraph emphasizing that IFN induction is stochastic for all viral mutants.
