### ISSUE TITLE
emphasize how gene absence is called

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/IFNsorted_flu_single_cell#24]
There is a paragraph in results about this, but two readers (or the same reader twice) have missed it. Make sure it is very obvious.

**Comment by abr28** [comment]
Agreed. Maybe just a supplemental schematic? Could mock something up (loose schematic showing extracellular sampling during process to better conceptualize it?)

**Comment by jbloom** [comment]
Now re-stated again.

At this point, I don't think we need an additional figure since the reviewer didn't say that they misunderstood it, but simply that they somehow missed the text.
