### ISSUE TITLE
clearly emphasize that IFN remains stochastic in NS+ and NS- cells

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/IFNsorted_flu_single_cell#26]
This is stated, but possibly should be stated even more clearly.

**Comment by abr28** [comment]
I was thinking we could emphasize this for ALL mutants we test (and can cite prior work from Randall), and then transition to the burden and ribavirin to partially explain remaining IFN induction? Can do a sub-figure in supplement showing all NS- IFN+ and IFN- cells and genotypes. No statistical argument to be made, but at least an evocative one showing no single defining genetic characteristic driving non-deterministic behavior.

**Comment by jbloom** [comment]
Text in the genotypes section now clearly calls out that there are NS- cells that don't induce IFN.
